# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfBirth', models.IntegerField()),
                ('gender', models.CharField(max_length=1000)),
                ('symptom', models.CharField(max_length=5000)),
            ],
        ),
    ]
