# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='file',
            name='symptom',
            field=models.CharField(max_length=1000),
        ),
    ]
